### ISSUE TITLE
Missing 'All/Uncategorized' category

### ISSUE THREAD

**Issue by Savasdotexe** [GChristensen/torrent-add#11]
In the event user wishes to not set a category, they are forced to pick one just to be able to add the torrent, as there seems to be no All or Uncategorized option.

Is it possible for the user to also be able to create a category? Also if there's a way to allow user to refresh/update the category list without going into the settings that would be great, maybe just before adding a torrent?

EDIT: noticed in [this screenshot](https://lh3.googleusercontent.com/RvnrhvMZZo9ItjRB-XGJvnSa9jg_PsFLOmRxfTPcqXV4z9lSFu43-NcSIwQsPf33cRYBhxG1T1mu1YUaJX2AphtT4Jo=s1280-w1280-h800) on chrome store it shows [root], I'm guessing this is the all/uncategorized? Was this manually created or?

**Comment by GChristensen** [comment]
Hi, This category presents by default and places downloads to the root directory, where other category folders are located. You can manually create an "uncategorized" folder or category if you use the client categories.

**Comment by Savasdotexe** [comment]
I am using "torrent client categories". I do not have the [root], I had to create a category called "uncategorized". That was my point.

It's liveable, but I just thought this was something that was worth adding or fixing. Is it possible to add the ability to create a category?

Additionally, as mentioned, it would be nice if when you add a torrent it auto refreshes the list, so you don't have to go into settings to get it to trigger a refresh.
