### ISSUE TITLE
[Feature Request] Option to left clicking Icon which opens the webui URL

### ISSUE THREAD

**Issue by Savasdotexe** [GChristensen/torrent-add#12]
Very useful to have, when you left click on the Icon it automatically opens the webui URL. Saves on having to manually type of use a bookmark.

P.S. Thank you for this nice extension.

**Comment by GChristensen** [comment]
Can you describe your use case,, why do you need to access the options page often? This is an utility settings page that is not meant to be accessed often. You may manage categories from torrent client if you select the corresponding option, or there may be a better solution, depending on use case.
If you're on Firefox, there is add-on that allows to place a button with custom icon on any browser bar: https://addons.mozilla.org/en-US/firefox/addon/multibutton/
You can place the bookmark with options link to the bookmark bar.

**Comment by Savasdotexe** [comment]
I think you may have misunderstood me.

To describe my use case, basically when I left click on the extension icon, I'd like it to open the WebUI URL, which would be the main page of my qBittorrent Web UI first page. This would help speed up the process of opening the remote qBittorrent.

The left click on the extension icon is unused, yes I could use another extension, but this feels more intuitive to simply go to when thinking about the remote qbittorrent. I hope that clears it up.

**Comment by GChristensen** [comment]
It's an interesting idea. I'll try to implement in the near future.

**Comment by GChristensen** [comment]
This will be added in the next version 0.5 soon.
