### ISSUE TITLE
PLEASE add some indication if it's connected!

### ISSUE THREAD

**Issue by ckramer** [GChristensen/torrent-add#13]
This is the best torrent extension, thank you!

But such pain to use it because there's no indication if it's connected or not.  it may lose connection to qbittorrent and you may be adding torrents but they go nowhere and there's no indication.  
And to connect I go to options click the power plug icon, and refresh many times. and then to test if it connected I try to add torrent, then go to qbittorrent to check if it added. If not open extension options and click refresh again and again.

Earlier it was possible to know if it's connected because it populated categories from client. And when you add it will show empty list "add to". 
Now it doesn't erase categories when it lost connection. and you add torrents thinking all is fine to find hour later that all 20 torrents you added went nowhere and all list. And then again, go to extension options, and click refresh , reload it endlessly until it may work or not.

Please add some feedback to show if it's connected or failed! 
When adding, maybe notification "successfully added". Or at least on Addon options some text if there's error connecting.

**Comment by GChristensen** [comment]
Hi, the extension obligatory notifies when it can not add a torrent because the torrent can not be downloaded or the client is unreachable. I'll try to investigate this.

**Comment by ckramer** [comment]
Notifies with browser notification or some other method?

**Comment by ckramer** [comment]
Ok, I get this "Add torrent notification". I just thought it's from qbittorrent.
![image](https://github.com/GChristensen/torrent-add/assets/91363/20d80d8c-df64-4d9a-82a8-1421b28f521f)

But torrent is not added actually. And no "add torrent" in qbittorrent logs. While if I add torrent by other means, it appears in Qbit and Qbit log.

If I shut down qbit there's no notifications and categories disappear.
Could this mean "Add torrent" is not fully transactional event, so to say. It's sent to qbit's address successfully, but without acknowledgement that it was accepted?

**Comment by GChristensen** [comment]
No, it looks like this. I've checked, it appears (after some time, since it waits for connection timeout) if qbittorrent is shut down.
![Screenshot 2024-04-26 120202](https://github.com/GChristensen/torrent-add/assets/170405/fe1aafdd-eba7-4e72-9fe6-da97ac65e222)

**Comment by GChristensen** [comment]
Works both on chrome and firefox...
![Screenshot 2024-04-26 120644](https://github.com/GChristensen/torrent-add/assets/170405/a0807df3-0c87-42ec-a861-c5495b1a8459)

I'ts very strange that there is no proper notification text in your case. I guess, it's mac?

**Comment by ckramer** [comment]
This issue never went away for me. It just stops working and no indication why.
- qbittorrent opens fine when I click on extension icon. it's configured to allow all, it's local network, works for weeks and one day added torrents do not appear added. 
- in extension settings the only way to somehow get indication that it's connected is to load custom categories.  for that I nee dto remove server or add another one, then switch and categories will be empty and then it will populate categories meaning it's connected! but even after all that the torrent is silently not added. 
- Silently because I have set in preferences "notification on Not added". And that notification only works once per session. until you restart browser. after first failed adding , following attempts will eb completely silent, you never know if it was added unless you jump to qbittorrent to verify every time. but then you do all the work and what's the extension for.

1. Can we please have some indication that it 's connected!? 
2. Can in notification it show some info about what is the error?
3. Can it show notification more than once?

**Comment by GChristensen** [comment]
Hi, this may be either a local network issue or issue with expiration of qbittorrent cookies if it is used not much often (this requires investigation). If the latter is an issue and if it will be fixed, the current notification behavior is fairly enough. It is necessary to check if os browser notifications are muted somehow.
