### ISSUE TITLE
Success Notification Chrome 

### ISSUE THREAD

**Issue by alexeylutskov** [GChristensen/torrent-add#16]
Please add Success Notification Chrome

**Comment by GChristensen** [comment]
Hi, this is a controversial issue. Many consider excessive notification annoying. Although it is possible to add them as opt-in option.

**Comment by alexeylutskov** [comment]
Thanks for the quick response!

Adding it as an option would be an excellent solution, and the option itself will allow you to be sure that the torrent has been added; at the moment you have to check this manually.

**Comment by GChristensen** [comment]
The option should appear in the settings of v0.6.1 when it will pass Chrome Store review.

**Comment by alexeylutskov** [comment]
Thank you very much!
