### ISSUE TITLE
Still fails a small percentage of the time

### ISSUE THREAD

**Issue by bcurran3** [GChristensen/torrent-add#2]
REF: https://github.com/GChristensen/torrent-add/issues/1

I'm using v0.2.3 now.

- Most of the time it will not add on first try, almost always works on 2nd try
- It has added as low as 3 without fault, and as high as 8 before failing to add maglink to qbt
-

**Comment by GChristensen** [comment]
Which version of browser and qbt you use?

**Comment by GChristensen** [comment]
Anyway, try 0.2.4.

**Comment by bcurran3** [comment]
Using v0.2.5 today and just successfully added 23 torrents with no problems. I think you got it!
