### ISSUE TITLE
Changing directory to category?

### ISSUE THREAD

**Issue by PintjesB** [GChristensen/torrent-add#4]
Hi,

I was wondering if it isn't a better plan to use the categories for qbittorrent instead of the directory. You can set the directory for that category and that way it's actually labeled in the webgui... 

Thanks!

**Comment by GChristensen** [comment]
I'll think about this. This will require rework of the add-on options page. Not a quick task.

**Comment by GChristensen** [comment]
I've added the support of qBittorrent categories, although it is somewhat tricky to use. Please, refer the add-on help for more details. Some testing may still be required. On Chrome, it may be necessary to wait several days until the add-on is reviewed and become available in the store for the automatic update.
