### ISSUE TITLE
[Feature Request] Notification when adding

### ISSUE THREAD

**Issue by simonbcn** [GChristensen/torrent-add#5]
It would be very useful if the extension would display a notification whether the torrent has been added successfully or failed.

(_Thanks for this extension, it's very useful_)

**Comment by GChristensen** [comment]
Hi,

The add-on displays a notification in the case of fail. It is possible to add an optional notification when a torrent is added successfully, but people usually find such things annoying.

**Comment by simonbcn** [comment]
ok, I didn't know it showed a notification when it failed.
