### ISSUE TITLE
It's keep dancing when I open the options

### ISSUE THREAD

**Issue by ihipop** [GChristensen/torrent-add#7]
https://github.com/GChristensen/torrent-add/assets/423077/8869b2b6-e629-4b03-aa4f-f2f3c1844d5c

`version`: `0.4`
`chrome`:`117.0.5938.149`

**Comment by GChristensen** [comment]
Hi, this may be due to difference in Asian and Latin fonts, since this doesn't happen in the Chrome with the English locale. I've added fixed I could imagine, they will be available after the addon is updated.

**Comment by ihipop** [comment]
[this fix ](https://github.com/GChristensen/torrent-add/commit/03570690c9c22366037212ea06f3432b3e8db626) is working ， thanks for your work
