### ISSUE TITLE
First add will fail  after SID of qbittorrent is expired

### ISSUE THREAD

**Issue by ihipop** [GChristensen/torrent-add#8]
![image](https://github.com/GChristensen/torrent-add/assets/423077/2e166a9c-7198-46d3-bf5d-9077793967fd)

When the login cookie is expired， the first time of add a torrent will fail, until I add it again the second time
maybe we could   re-try login to login if we know the failure is because of the expiration of the login cookie

**Comment by GChristensen** [comment]
I'll try sometimes later. Personally I'm using auto login by network mask. This may be used as a workaround.

**Comment by ihipop** [comment]
this could be instantly recurred by login from the web UI of qBittorrent ， because it will expire the previous SID got by this addon previously

**Comment by ihipop** [comment]
> I've slightly reworked login in 0.4.2. Now it checks if WebIU is logged in and logs in only if it is not. Hope this will help. If not, I need a complete sequence of actions that leads to this error.

I see, it works like a charm now, I can share the SID of WebIU so I won't have to log in frequently
thanks for your great work
